### ISSUE TITLE
ommitted queryTime

### ISSUE THREAD

**Issue by ArtSphere** [Jake0303/InteractiveBrokersPythonBot#1]
Hey Jake, i just looked at your video and code. I like it a lot. 
What I have not understood in all detail, but believe is not correct is the handling of queryTime when requesting data, i.e. should not line 101:
        self.ib.reqHistoricalData(self.reqId,contract,"","2 D",str(self.barsize)+mintext,"TRADES",1,1,True,[])
correctly be: 
        self.ib.reqHistoricalData(self.reqId,contract, queryTime ,"2 D",str(self.barsize)+mintext,"TRADES",1,1,True,[])

Thank you for your great work

**Comment by sharpertrading** [comment]
Jake's code is just fine if you leave the queryTime out and use an empty string you get the most up to date available data.  Therefore you don't need it. endDateTime, The request's end date and time (the empty string indicates current present moment).
here is a link https://interactivebrokers.github.io/tws-api/historical_bars.html

**Comment by ArtSphere** [comment]
@sharpertrading Thank you, You are right, i missed that in the API spec. The only detail, that i would then still comment on that line 91 defines the variable queryTime that is not used:
        queryTime = (datetime.now().astimezone(pytz.timezone("America/New_York"))-timedelta(days=1)).replace(hour=16,minute=0,second=0,microsecond=0).strftime("%Y%m%d %H:%M:%S")
Thank you again. Great piece of work and awsome video too :-)
